---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 12
  data_path: test/shared

verifier:
  name: inspec

platforms:
  - name: centos-6.7
  - name: centos-7.1
  - name: centos-7.3
 # - name: ubuntu-14.04
 # - name: debian-8.0
 # - name: fedora-21
 # - name: windows-2012r2
 #   driver:
 #     box: dhoer/windows-2012r2
    attributes:
      java_se:
        force_i586: true

#suites:
#  - name: default
#    run_list:
#      - recipe[java_se::default]
#  - name: alt_home
#    run_list:
#      - recipe[java_se::default]
#    excludes:
#     - centos-7.1
#      - ubuntu-14.04
#      - debian-8.0
#      - fedora-21
#     - windows-2012r2
#   attributes:
#     java_se:
#       java_home:
#         C:\my\java\jdk
#       win_jre_home:
#         C:\my\java\jre
---


suites:
  - name: default
    run_list:
      - recipe[java_se::default]
  - name: alt_home
    run_list:
      - recipe[java_se::default]
    excludes:
      - centos-6.7
      - centos-7.1
      - centos-7.3
      - ubuntu-14.04
      - debian-8.0
      - fedora-21
    attributes:
      java_se:
        java_home:
          C:\my\java\jdk
        win_jre_home:
          C:\my\java\jre

